### ISSUE TITLE
multiple intersections

### ISSUE THREAD

**Issue by dusadrian** [poilu/raphael-boolean#8]
I was wondering if this library could be used for multiple intersections (more than 2).

Sometimes, I need something like:
notA and notB and C
(which basically is everything inside C that is not intersecting with A and also not intersecting with B)

What would be the proper usage of this library to achieve this?

If I manage to do this, I would also like to cite your library. What is the license under which you released it?

**Comment by poilu** [comment]
This should be possible by executing operations step by step, like this:
```javascript
var a = paper.path("...");
var b = paper.path("...");
var c = paper.path("...");
// calculate the difference of c and a
var dStr = paper.difference(c,a);
// create a new path out of the interim result
var d = paper.path(dStr);
// calcultate the difference of d and b
var eStr = paper.difference(d,b);
// create a new path out of the final result
var e = paper.path(eStr);
//TODO: remove a, b, c and d
```
A direct concatenation of operations isn't possible so far. Maybe this could be considered for a rework in the future.
The plugin is published under MIT licence. So you can use it the same way like Raphael itself. Citation is appreciated, but not mandatory.

**Comment by dusadrian** [comment]
Yes, that is almost what I've already come up with.
Manually, your code works but I need it for batch use, where I don't know which set is 1 (in the set) and which is 0 ("not" in the set).
The additional thing that I've done, which solves the problem, is to have yet another "box" which covers all three of them.

var box = paper.path("...");
var a = paper.path("...");
var b = paper.path("...");
var c = paper.path("...");

For "notA and notB and C" I do (simplified pseudo code):

set.difference(box, a);
then
set.difference(result, b);
then
set.intersection(result, c);

That works in the exact order of A, B and C, and should be working for any number of sets.
This is for an R package I am writing, called QCAGUI. In about a month I will release it, and of course proper citations will be given.
Thanks very much, great library!
